### ISSUE TITLE
Limited options

### ISSUE THREAD

**Issue by gregorkrambs** [geeseven/strawpoll-from-steam-wishlist#1]
Maybe you should try strawpoll.com, it does support up to 500 answer options per poll.

**Comment by geeseven** [comment]
Hey @gregorkrambs,

I created this script for a [Twitch][0] streamer.   Their workflow was to use strawpoll.me due to its integration with Twitch chat.  That streamer also never created a poll with more than a dozen games, so strawpoll.me limit is not an issue.  

[0]: https://www.twitch.tv/
